name : Que1 

on :
  push :
    branches : [main]

jobs :
    build :
      runs-on:  "ubuntu-latest"

      steps :
        - name : CheckoutCode
          uses : actions/checkout@v3
        - name : BuildPython
          uses : actions/setup-python@v4
          with :
            python-version : "3.10" 
        - name : Install Depedencies
          run : |
            if [-f requirements.txt]; then
              echo "files found"
              pip install -r requirements.txt
            else 
              echo "files not found"
            fi 
        - name : Greet
          run : | 
            echo "Hi"

          